services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: mariadb:latest
    container_name: chatapp_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: chatdb
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: chatpassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: chatapp_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: chatuser
      PMA_PASSWORD: chatpassword
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  mariadb_data: